version: '3.7'

volumes:
  postgres:

services:
  chat-database:
    container_name: chat-database
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "chat"
      POSTGRES_PASSWORD: 'chat1234'
      PGDATA: "/data/postgres"
    volumes:
      - ./chatDB:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5431:5432"
    restart: unless-stopped
